name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Checkout content repository
        uses: actions/checkout@v4
        with:
          repository: danfascia/blog
          path: _temp_blog_content
          token: ${{ secrets.CONTENT_REPO_PAT }}

      - name: Copy content folders
        run: |
          rm -rf src/content/posts
          rm -rf src/content/pages
          mkdir -p src/content/posts
          mkdir -p src/content/pages
          cp -r _temp_blog_content/posts/* src/content/posts/
          cp -r _temp_blog_content/pages/* src/content/pages/

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Astro project
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: master
          force_orphan: true
